language: ruby
rvm:
- 2.0.0
cache: bundler
before_script:
  - psql -c 'create databse cats_test;' -U postgres
  - bundle exec rake db:migrate db:test:prepare

addons:
  code_climate:
    repo_token: 7b0290ef01d78fc9057436906e29c067b9edf073370d33c0799a824bf4f71f75

